name: CI
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    # Checks-out the repository under $GITHUB_WORKSPACE
    - uses: actions/checkout@v2

    # Install Node Js
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        
    # Install Node Modules
    - name: Install Node Modules
      run: yarn install --frozen-lockfile

    # Runs a set of commands using the runners shell
    - name: Runs Unit Tests
      run: yarn test
